### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Lim-YoungYoon** [Troyanovsky/stable_diffusion_prompt_optimizer#1]
.

**Comment by Troyanovsky** [comment]
See section 1: You need to convert the data into pkl first.

**Comment by Troyanovsky** [comment]
serratus anterior

**Comment by Troyanovsky** [comment]
See section 1: You need to convert the data into pkl first.

**Comment by Lim-YoungYoon** [comment]
plz delete this issue :)
