### ISSUE TITLE
No such file or directory: artists_vector.pkl

### ISSUE THREAD

**Issue by Niptlox** [Troyanovsky/stable_diffusion_prompt_optimizer#2]
Traceback (most recent call last):
  File "D:\PythonProjects\!AI\BooksAnimate\PromptOptimizer.py", line 86, in <module>
    with open(os.path.join(folder_path, "artists_vector.pkl"), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'stable_diffusion\\artists_vector.pkl'

**Comment by Troyanovsky** [comment]
Hi, to use the notebook, first read and run the pre-req section, put the tags files from Github (https://github.com/Troyanovsky/stable_diffusion_prompt_optimizer) into your google drive. The script will convert the txt files from [stable_diffusion_prompt_optimizer](https://github.com/Troyanovsky/stable_diffusion_prompt_optimizer/tree/main)
/tags/ into pkl files to be used in later sections.
